server:
  port: 8090

spring:
  application:
    name: kotlin-examples
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ENC(sOmPDjm2JtFMe8ITpme3NCDcK4b15zUi4DOh+R/Si4aAFGn+ZbHvh+xW2IrdKu2ecMtFC81kxdN+UWZ3lpyMtWrQm2OH/VGxsL6h/rNwW6D41Pk5OwdcNvTZRN3jueUx5T42HCRdS2ndJ7P9D/Avkp0D11JvF1Bx4rgrmHKqBCz+Iv40mB2tygOq8SBJq0Y0IQ7vcdLZFqpe8u3AfLFlEuwuvffmMvn+rGIE2h/YusyZZ8HaHokLZSC4MleDG1W8)
    username: ENC(PnOVAen15dOTewHYXC5/5g==)
    password: ENC(M5SpZxPEkU9FTDy+eW8yhamP1ZZ7utHy)
  redis:
    database: 15
    host: ENC(OlmpxaA9LXoI/KNt+lFfaYQY5dEQtLA0)
    port: 6379
    password: ENC(ukG21OjLJaT2HwdlXW2gLgT9BJ8j2RFo)
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml

jasypt:
  encryptor:
    # 加密时的盐值
    password: ${spring.application.name}

logging:
  level:
    # mapper 日志输出
    org.example.hello.mapper: debug